dibimbing:
  outputs:
    dev:
      dataset: star_schema
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ./creds/service_account.json
      location: US
      method: service-account
      priority: interactive
      project: dibimbing-alrappie
      threads: 1
      type: bigquery
  target: dev
